version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --config _config.yml
    image: jekyll/jekyll:3.7.3
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000